# Generated by Django 4.2 on 2023-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "مخاطب", "verbose_name_plural": "مخاطبین"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=100, verbose_name="شماره تماس"),
        ),
    ]
