# Generated by Django 4.2 on 2023-04-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0002_alter_contact_options_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شماره تماس"
            ),
        ),
    ]
