# Generated by Django 4.2 on 2023-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0003_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramworker",
            name="baned_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="محرومیت تا"
            ),
        ),
    ]
