# Generated by Django 4.2 on 2023-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0004_telegramworker_baned_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="has_telegram",
            field=models.BooleanField(default=False, verbose_name="دارای تلگرام"),
        ),
    ]
