# Generated by Django 4.2 on 2023-04-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0005_contact_has_telegram"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramworker",
            name="add_contact_today",
            field=models.IntegerField(default=0, verbose_name="مخاطب اضافه شده امروز"),
        ),
        migrations.AddField(
            model_name="telegramworker",
            name="message_sent_today",
            field=models.IntegerField(default=0, verbose_name="پیام ارسال شده امروز"),
        ),
    ]
