# Generated by Django 4.2 on 2023-04-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("from_tag", models.CharField(max_length=100)),
                ("is_business", models.BooleanField(default=False)),
                ("other_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_working", models.BooleanField(default=False)),
            ],
        ),
    ]
