# Generated by Django 4.2 on 2023-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hashtagbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountinfo",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
