# Generated by Django 4.2 on 2023-04-14 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hashtagbot", "0003_accountinfo_user_worker_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountinfo",
            options={"verbose_name": "اکانت", "verbose_name_plural": "اکانت ها"},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "کارگر", "verbose_name_plural": "کارگران"},
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="from_tag",
            field=models.CharField(max_length=100, verbose_name="هشتگ"),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="is_business",
            field=models.BooleanField(default=False, verbose_name="اکانت کسب و کار"),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="is_checked",
            field=models.BooleanField(default=False, verbose_name="بررسی شده"),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="other_info",
            field=models.TextField(verbose_name="اطلاعات دیگر"),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="phone_number",
            field=models.CharField(max_length=100, verbose_name="شماره تلفن"),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="username",
            field=models.CharField(max_length=100, verbose_name="نام کاربری"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="is_working",
            field=models.BooleanField(default=False, verbose_name="در حال کار"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="password",
            field=models.CharField(max_length=100, verbose_name="رمز عبور"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="username",
            field=models.CharField(max_length=100, verbose_name="نام کاربری"),
        ),
    ]
